- name: Run Terraform Infrastructure
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Terraform init
      command: terraform init
      args:
        chdir: "{{ playbook_dir }}/../../terraform"

    - name: Terraform apply
      command: terraform apply -auto-approve
      args:
        chdir: "{{ playbook_dir }}/../../terraform"

    - name: Refresh inventory after Terraform
      meta: refresh_inventory
      
    - name: Show Terraform outputs
      ansible.builtin.command: terraform output
      args:
        chdir: "{{ playbook_dir }}/../../terraform"
      register: terraform_outputs
      changed_when: false

    - name: Print Terraform outputs
      ansible.builtin.debug:
        var: terraform_outputs.stdout_lines

