- name: Install Kubernetes using Kubespray
  hosts: localhost
  gather_facts: false

  vars:
    kubespray_dir: "{{ playbook_dir }}/../../kubespray"
    venv_path: "{{ kubespray_dir }}/venv"

  tasks:
    - name: Create virtualenv
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Install requirements
      command: "{{ venv_path }}/bin/pip install -r requirements.txt"
      args:
        chdir: "{{ kubespray_dir }}"

    - name: Run Kubespray with venv
      command: >
        {{ venv_path }}/bin/ansible-playbook
        -i ../ansible/inventory/inventory
        cluster.yml
      args:
        chdir: "{{ kubespray_dir }}"