- name: Cleanup Terraform Infrastructure
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Destroy master and worker nodes
      ansible.builtin.command: terraform destroy -auto-approve
      args:
        chdir: "{{ playbook_dir }}/../../terraform"