# Registry mirrors and optional auth for containerd
containerd_registries_mirrors:
  - prefix: "docker.io"
    mirrors:
      - host: "https://registry-1.docker.io"
        capabilities: ["pull", "resolve"]

# If you want Kubespray to configure node-level auth, place
# credentials here. Prefer using Ansible Vault instead of plain text.
containerd_registry_auth:
  docker.io:
    username: "jorgennonstad"
    password: "dockerPassword123"
